# Generated by Django 4.2.4 on 2023-10-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0061_rename_image_story_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image1',
            new_name='image',
        ),
    ]
